import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Files,
  Folders,
  User2Icon,
} from "lucide-react";
import { IconType } from "react-icons/lib";
import { FaTerminal, FaEthereum, FaCode } from "react-icons/fa";
import { RiGeminiFill } from "react-icons/ri";
import { LuBookText, LuFileCode2, LuMail } from "react-icons/lu";
import { TbSmartHome } from "react-icons/tb";
import { UUID } from "crypto";

export const sidebar_data = {
  logo: "/logo.png",
  navMain: [
    {
      title: "Home",
      url: "/",
      icon: TbSmartHome,
      isActive: false,
    },
    {
      title: "Blogs",
      url: "/blogs",
      icon: Files,
      isActive: false,
    },
    {
      title: "Projects",
      url: "/projects",
      icon: Folders,
      isActive: false,
    },
    {
      title: "Practice",
      url: "/practice",
      icon: LuFileCode2,
      isActive: false,
    },
    {
      title: "Courses",
      url: "/courses",
      icon: LuBookText,
      isActive: false,
    },
  ],
  bottomMain: [
    {
      title: "About",
      url: "/about",
      icon: User2Icon,
      isActive: false,
    },
    {
      title: "Subscribe",
      url: "/subscribe",
      icon: LuMail,
      isActive: false,
    },
  ],
};

export const alltags = [
  { label: "Array", value: "Array" },
  { label: "String", value: "String" },
  { label: "Hash Table", value: "Hash Table" },
  { label: "Dynamic Programming", value: "Dynamic Programming" },
  { label: "Math", value: "Math" },
  { label: "Sorting", value: "Sorting" },
  { label: "Greedy", value: "Greedy" },
  { label: "Depth-First Search", value: "Depth-First Search" },
  { label: "Database", value: "Database" },
  { label: "Binary Search", value: "Binary Search" },
  { label: "Matrix", value: "Matrix" },
  { label: "Tree", value: "Tree" },
  { label: "Breadth-First Search", value: "Breadth-First Search" },
  { label: "Bit Manipulation", value: "Bit Manipulation" },
  { label: "Two Pointers", value: "Two Pointers" },
  { label: "Prefix Sum", value: "Prefix Sum" },
  { label: "Heap (Priority Queue)", value: "Heap (Priority Queue)" },
  { label: "Binary Tree", value: "Binary Tree" },
  { label: "Simulation", value: "Simulation" },
  { label: "Stack", value: "Stack" },
  { label: "Graph", value: "Graph" },
  { label: "Counting", value: "Counting" },
  { label: "Sliding Window", value: "Sliding Window" },
  { label: "Design", value: "Design" },
  { label: "Backtracking", value: "Backtracking" },
  { label: "Enumeration", value: "Enumeration" },
  { label: "Union Find", value: "Union Find" },
  { label: "Linked List", value: "Linked List" },
  { label: "Ordered Set", value: "Ordered Set" },
  { label: "Number Theory", value: "Number Theory" },
  { label: "Monotonic Stack", value: "Monotonic Stack" },
  { label: "Trie", value: "Trie" },
  { label: "Segment Tree", value: "Segment Tree" },
  { label: "Bitmask", value: "Bitmask" },
  { label: "Queue", value: "Queue" },
  { label: "Divide and Conquer", value: "Divide and Conquer" },
  { label: "Recursion", value: "Recursion" },
  { label: "Combinatorics", value: "Combinatorics" },
  { label: "Binary Indexed Tree", value: "Binary Indexed Tree" },
  { label: "Geometry", value: "Geometry" },
  { label: "Binary Search Tree", value: "Binary Search Tree" },
  { label: "Hash Function", value: "Hash Function" },
  { label: "Memoization", value: "Memoization" },
  { label: "String Matching", value: "String Matching" },
  { label: "Topological Sort", value: "Topological Sort" },
  { label: "Shortest Path", value: "Shortest Path" },
  { label: "Rolling Hash", value: "Rolling Hash" },
  { label: "Game Theory", value: "Game Theory" },
  { label: "Interactive", value: "Interactive" },
  { label: "Data Stream", value: "Data Stream" },
  { label: "Monotonic Queue", value: "Monotonic Queue" },
  { label: "Brainteaser", value: "Brainteaser" },
  { label: "Randomized", value: "Randomized" },
  { label: "Merge Sort", value: "Merge Sort" },
  { label: "Doubly-Linked List", value: "Doubly-Linked List" },
  { label: "Counting Sort", value: "Counting Sort" },
  { label: "Iterator", value: "Iterator" },
  { label: "Concurrency", value: "Concurrency" },
  { label: "Probability and Statistics", value: "Probability and Statistics" },
  { label: "Quickselect", value: "Quickselect" },
  { label: "Suffix Array", value: "Suffix Array" },
  { label: "Bucket Sort", value: "Bucket Sort" },
  { label: "Minimum Spanning Tree", value: "Minimum Spanning Tree" },
  { label: "Line Sweep", value: "Line Sweep" },
  { label: "Shell", value: "Shell" },
  { label: "Reservoir Sampling", value: "Reservoir Sampling" },
  {
    label: "Strongly Connected Component",
    value: "Strongly Connected Component",
  },
  { label: "Eulerian Circuit", value: "Eulerian Circuit" },
  { label: "Radix Sort", value: "Radix Sort" },
  { label: "Rejection Sampling", value: "Rejection Sampling" },
  { label: "Biconnected Component", value: "Biconnected Component" },
];

export const difficulties = [
  {
    label: "Easy",
    value: "Easy",
    iconColour: "text-green-500",
    icon: <ArrowDown className={`mr-2 h-4 w-4  text-green-500`} />,
  },
  {
    label: "Medium",
    value: "Medium",
    iconColour: "text-yellow-500",
    icon: <ArrowRight className={`mr-2 h-4 w-4  text-yellow-500`} />,
  },
  {
    label: "Hard",
    value: "Hard",
    iconColour: "text-red-500",
    icon: <ArrowUp className={`mr-2 h-4 w-4 text-red-500`} />,
  },
];

export type practiceType = {
  id: UUID;
  prefix: string;
  exid: number;
  difficulty: "Easy" | "Medium" | "Hard";
  isFavor: boolean;
  status: "Done" | "Attempt" | "Unattempt";
  title: string;
  titleSlug: string;
  topicTags: string[];
  hasSolution: boolean;
  hasVideoSolution: boolean;
  content: (string | string[])[];
};

export const practices: practiceType[] = [
  {
    id: "F55F2E2F-78E9-40CB-B23B-C8CB0741EC8C",
    prefix: "LC",
    exid: 27,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Remove Element",
    titleSlug: "remove-element",
    topicTags: ["Array", "Two Pointers"],
    hasSolution: true,
    hasVideoSolution: false,
    content: ["Question", "Solution"],
  },
  {
    id: "E02DD495-8A06-4F75-9517-8EF7D74A2097",
    prefix: "LC",
    exid: 88,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Merge Sorted Array",
    titleSlug: "merge-sorted-array",
    topicTags: ["Array", "Two Pointers", "Sorting"],
    hasSolution: true,
    hasVideoSolution: false,
    content: ["Question", "Solution"],
  },
  {
    id: "CD6A55E6-8785-43E8-9E64-AAEF215DD00A",
    prefix: "LC",
    exid: 1,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Two Sum",
    titleSlug: "two-sum",
    topicTags: ["Array", "Hash Table"],
    hasSolution: true,
    hasVideoSolution: false,
    content: ["Brute Force", "Hash Map", "Explanation"],
  },
  {
    id: "BB12023F-488C-488C-A55C-313E04CD4AF2",
    prefix: "LC",
    exid: 1415,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "The k-th Lexicographical String of All Happy Strings of Length n",
    titleSlug:
      "the-k-th-lexicographical-string-of-all-happy-strings-of-length-n",
    topicTags: ["String", "Backtracking"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Combinatorics",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "E82C250C-F4DC-48CE-8E9C-FB9B2C7F2361",
    prefix: "LC",
    exid: 1752,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Check if Array Is Sorted and Rotated",
    titleSlug: "check-if-array-is-sorted-and-rotated",
    topicTags: ["Array"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      ["Approach", "Example Walkthrough", "Complexity Analysis"],
    ],
  },
  {
    id: "DD9511E7-4B5C-4A4C-A32E-19544E6DB68F",
    prefix: "LC",
    exid: 1790,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Check if One String Swap Can Make Strings Equal",
    titleSlug: "check-if-one-string-swap-can-make-strings-equal",
    topicTags: ["Hash Table", "String", "Counting"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      [
        "Check Length Equality and Immediate Equality",
        "Using Hash Maps and a Counter",
        "Loop Through the Strings",
        "Verify Character Frequencies",
      ],
      "Complexity Analysis",
    ],
  },
  {
    id: "CE6325CC-A893-471C-998B-99D5134B59E4",
    prefix: "LC",
    exid: 1800,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Maximum Ascending Subarray Sum",
    titleSlug: "maximum-ascending-subarray-sum",
    topicTags: ["Array"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      ["Approach", "Example Walkthrough", "Complexity Analysis"],
    ],
  },
  {
    id: "9C038F58-7EA4-404B-9D5B-8B355732F1AC",
    prefix: "LC",
    exid: 1910,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Remove All Occurrences of a Substring",
    titleSlug: "remove-all-occurrences-of-a-substring",
    topicTags: ["String", "Stack", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Stack",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "667B93AB-9E3B-402B-B6C0-9D6C62FA177E",
    prefix: "LC",
    exid: 3151,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Special Array I",
    titleSlug: "special-array-i",
    topicTags: ["Array"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      ["Approach", "Example Walkthrough", "Complexity Analysis"],
    ],
  },
  {
    id: "64593DE5-F5DA-4908-8039-F5DC30958C55",
    prefix: "LC",
    exid: 3105,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Longest Strictly Increasing or Strictly Decreasing Subarray",
    titleSlug: "longest-strictly-increasing-or-strictly-decreasing-subarray",
    topicTags: ["Array"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      ["Approach", "Example Walkthrough", "Complexity Analysis"],
    ],
  },
  {
    id: "366597DD-58C2-4849-AF4B-A0B87EB7134C",
    prefix: "LC",
    exid: 1726,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Tuple with Same Product",
    titleSlug: "tuple-with-same-product",
    topicTags: ["Array", "Hash Table", "Counting"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      [
        "Counting Products",
        "Iterating Over Pairs",
        "Calculating the Result",
        "Return the Result",
      ],
      "Complexity Analysis",
    ],
  },
  {
    id: "EB8C4460-6767-47C2-95AD-127475ED0469",
    prefix: "LC",
    exid: 3160,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Find the Number of Distinct Colors Among the Balls",
    titleSlug: "find-the-number-of-distinct-colors-among-the-balls",
    topicTags: ["Array", "Hash Table", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      ["Initial Setup", "Processing Each Query"],
      "Complexity Analysis",
    ],
  },
  {
    id: "DBF51A2B-50DC-45DD-88EA-8A0B5C4D0361",
    prefix: "LC",
    exid: 2364,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Count Number of Bad Pairs",
    titleSlug: "count-number-of-bad-pairs",
    topicTags: ["Array", "Hash Table", "Math", "Counting"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      "The Key Observation",
      "Step-by-Step Explanation",
      "Complexity Analysis",
    ],
  },
  {
    id: "081E6BCE-0C83-44B7-B792-B068D8F9A4A8",
    prefix: "LC",
    exid: 3174,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Clear Digits",
    titleSlug: "clear-digits",
    topicTags: ["String", "Stack", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Solution",
      "Explanation",
      [
        "1. Iteration and Stack Building",
        "2. Edge Case Handling",
        "3. Example Walkthrough",
      ],
      "Complexity Analysis",
    ],
  },
  {
    id: "2075189F-EDDF-44AD-BA42-8468B9F8F683",
    prefix: "LC",
    exid: 2342,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Max Sum of a Pair With Equal Sum of Digits",
    titleSlug: "max-sum-of-a-pair-with-equal-sum-of-digits",
    topicTags: ["Array", "Hash Table", "Sorting", "Heap (Priority Queue)"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Store Maximum Value",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "0A0FE867-CC6C-42D1-AC7A-D4120B2E2288",
    prefix: "LC",
    exid: 3065,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Minimum Operations to Exceed Threshold Value I",
    titleSlug: "minimum-operations-to-exceed-threshold-value-i",
    topicTags: ["Array"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "F0C431CA-C10D-447F-B371-1E60C4848D0D",
    prefix: "LC",
    exid: 3438,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Find Valid Pair of Adjacent Digits in String",
    titleSlug: "find-valid-pair-of-adjacent-digits-in-string",
    topicTags: ["Hash Table", "String", "Counting"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "60A2200F-FEED-422A-8653-8079131EE819",
    prefix: "LC",
    exid: 2460,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Apply Operations to an Array",
    titleSlug: "apply-operations-to-an-array",
    topicTags: ["Array", "Two Pointers", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Brute Force Simulation",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "One Pass",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "CD536EF3-7D4B-4643-88B9-6568B43A6CE0",
    prefix: "LC",
    exid: 1757,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Recyclable and Low Fat Products",
    titleSlug: "recyclable-and-low-fat-products",
    topicTags: ["Database"],
    hasSolution: true,
    hasVideoSolution: false,
    content: ["Question", "Selecting rows based on conditions", "Wrap up"],
  },
  {
    id: "A8CE6AB8-4921-4717-BBE5-9D28A8AF27AC",
    prefix: "LC",
    exid: 2570,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Merge Two 2D Arrays by Summing Values",
    titleSlug: "merge-two-2d-arrays-by-summing-values",
    topicTags: ["Array", "Hash Table", "Two Pointers"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach 1: Hash Map",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Approach 2: Two Pointers",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "288F628B-A8EA-47FF-B58F-C7864CC75307",
    prefix: "LC",
    exid: 2161,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Partition Array According to Given Pivot",
    titleSlug: "partition-array-according-to-given-pivot",
    topicTags: ["Array", "Two Pointers", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach 1: Dynamic Slices",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "54434067-1175-418F-AE0D-3B793E860121",
    prefix: "LC",
    exid: 1780,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Check if Number is a Sum of Powers of Three",
    titleSlug: "check-if-number-is-a-sum-of-powers-of-three",
    topicTags: ["Math"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Ternary Representation",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "B028C06D-1C38-4EA7-8FF5-8AE020BD7D5C",
    prefix: "LC",
    exid: 2579,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Count Total Number of Colored Cells",
    titleSlug: "count-total-number-of-colored-cells",
    topicTags: ["Math"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Mathematical Formula",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "C73027B3-6621-478C-8458-1B430B15BBC0",
    prefix: "LC",
    exid: 2356,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Number of Unique Subjects Taught by Each Teacher",
    titleSlug: "number-of-unique-subjects-taught-by-each-teacher",
    topicTags: ["Database"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Grouping and Counting Unique Subjects",
      ["Intuition", "Algorithm"],
      "Wrap up",
    ],
  },
  {
    id: "E18D5159-7FD1-4F73-B2E4-3DFE529D3C27",
    prefix: "LC",
    exid: 2965,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Find Missing and Repeated Values",
    titleSlug: "find-missing-and-repeated-values",
    topicTags: ["Array", "Hash Table", "Math", "Matrix"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Hash Map Counting",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "91343EB7-919B-4634-84EA-3D90EFC8EC31",
    prefix: "LC",
    exid: 2206,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Divide Array Into Equal Pairs",
    titleSlug: "divide-array-into-equal-pairs",
    topicTags: ["Array", "Hash Table", "Bit Manipulation", "Counting"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Hash Map",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "075F9465-8938-4C00-BF56-B09319813EAB",
    prefix: "LC",
    exid: 3417,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Zigzag Grid Traversal With Skip",
    titleSlug: "zigzag-grid-traversal-with-skip",
    topicTags: ["Array", "Matrix", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Traversal With Skip",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "C096230A-B4A7-4BF5-A65B-32D7B5991F97",
    prefix: "LC",
    exid: 2427,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Number of Common Factors",
    titleSlug: "number-of-common-factors",
    topicTags: ["Math", "Enumeration", "Number Theory"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Brute Force Iteration",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "6CFB0055-BB34-4B08-BDD7-CF1EE12CE6C7",
    prefix: "LC",
    exid: 2303,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Calculate Amount Paid in Taxes",
    titleSlug: "calculate-amount-paid-in-taxes",
    topicTags: ["Array", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Iterative Simulation",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "A00E1F5C-F023-4D32-9975-E82CA7D23F31",
    prefix: "LC",
    exid: 1688,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Count of Matches in Tournament",
    titleSlug: "count-of-matches-in-tournament",
    topicTags: ["Math", "Simulation"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Simulation",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "0F38B20D-E083-4CC2-AB3A-0F3C2901CFE1",
    prefix: "LC",
    exid: 2644,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Find the Maximum Divisibility Score",
    titleSlug: "find-the-maximum-divisibility-score",
    topicTags: ["Array"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Brute Force with Optimization",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "8359C781-9958-4FC8-AC4B-4B4D25902821",
    prefix: "LC",
    exid: 2140,
    difficulty: "Medium",
    isFavor: false,
    status: "Done",
    title: "Solving Questions With Brainpower",
    titleSlug: "solving-questions-with-brainpower",
    topicTags: ["Array", "Dynamic Programming"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Dynamic Programming",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
  {
    id: "25AFE42F-996F-426E-8419-F6CB7E32DF49",
    prefix: "LC",
    exid: 344,
    difficulty: "Easy",
    isFavor: false,
    status: "Done",
    title: "Reverse String",
    titleSlug: "reverse-string",
    topicTags: ["Two Pointers", "String"],
    hasSolution: true,
    hasVideoSolution: false,
    content: [
      "Question",
      "Approach: Two-Pointer Technique",
      ["Intuition", "Algorithm", "Complexity Analysis"],
      "Wrap up",
    ],
  },
];

export const blogCategories: {
  icon: IconType;
  classname: string;
  label: string;
  value: string;
}[] = [
  {
    icon: FaTerminal,
    classname: "fill-green-500",
    label: "Backend",
    value: "backend",
  },
  // { icon:  ,label: "Full-Stack", value: "full-stack" },
  {
    icon: FaEthereum,
    classname: "fill-blue-500",
    label: "Blockchain",
    value: "blockchain",
  },
  {
    icon: RiGeminiFill,
    classname: "fill-orange-500",
    label: "AI & Machine Learning",
    value: "ai-machine-learning",
  },
  {
    icon: FaCode,
    classname: "fill-blue-500",
    label: "Frontend",
    value: "frontend",
  },
];

export const blogs: blogsType[] = [
  {
    id: "ED951E39-1C6E-42DA-A842-53806580F2EA",
    title:
      "How to Change the Default Permission String for the Location-Access Alert in Expo",
    description:
      "Learn how to customize the default permission string for the location access alert in Expo applications, ensuring a better user experience.",
    titleSlug:
      "how-to-change-the-default-permission-string-for-the-location-access-alert-in-expo",
    date: "Jul 19, 2025",
    category: "frontend",
    content: [
      "The Problem",
      "The Fix: Clean Prebuild + EAS Build",
      "Why This Works",
      "Wrap up",
    ],
  },
  {
    id: "E6837422-93A6-431D-AA66-DAEC1D9F4D7B",
    title: "Run Stable Diffusion on Your MacBook M1 Using Python",
    description:
      "Turn your MacBook M1 into an art machine with Python, watch your words come to life in vivid images!",
    titleSlug: "run-stable-diffusion-on-your-macBook-m1-using-python",
    date: "Feb 10, 2025",
    category: "ai-machine-learning",
    content: [
      "Project Setup",
      [
        "Creating a Virtual Environment",
        "Adding Dependencies",
        "Create a Python File",
      ],
      "Generate AI Image",
      ["Code Implementation", "Execution", "Explanation"],
      "Wrap up",
    ],
  },
  {
    id: "68ADEA00-C482-465C-BFBC-B5B3392CA274",
    title: "Build your Golang Proxy Server",
    description:
      "Learn to build a robust Go proxy server supporting HTTP and HTTPS, complete with health checks and detailed logging.",
    titleSlug: "build-your-golang-proxy-server",
    date: "Feb 8, 2025",
    category: "backend",
    content: [
      "Prerequisites",
      "Project Setup",
      "Writing the Proxy Program",
      "Overview of main.go",
      [
        "Configuring the Server Port",
        "Implementing a Health Check Endpoint",
        "Initializing the Proxy Server",
        "Full Code (main.go)",
      ],
      "Overview of proxy.go",
      [
        "Resolving Host IP Addresses",
        "Extracting the Host from an HTTP Request",
        "Handling Client Requests",
        "Handling HTTPS Traffic",
        "Handling HTTP Requests",
        "Full Code (proxy.go)",
      ],
      "Running the Proxy",
      ["Configuring the Proxy on macOS"],
      "Stop the Proxy",
      "Wrap up",
    ],
  },
  {
    id: "3984BC66-D909-4074-BA7A-B7D6B07E7CBF",
    title: "Simple way to run deepseek-r1 Locally",
    description:
      "Learn how to install and use DeepSeek-R1, a lightweight, distilled AI model, with the open-source Ollama tool.",
    titleSlug: "simple-way-to-run-deepseek-r1-locally",
    date: "Feb 4, 2025",
    category: "ai-machine-learning",
    content: ["Installation", "Usages", "Wrap up"],
  },
  {
    id: "C19F6ABB-2DBD-47B1-AF6A-F02584029CD3",
    title: "Learn basics of SQLite",
    description:
      "SQLite is a lightweight, serverless, and self-contained relational database management system. It's often used in applications that need a local database.",
    titleSlug: "learn-basics-of-sqlite",
    date: "Aug 25, 2023",
    category: "backend",
    content: [
      "Installation",
      "Opening a Database",
      "Creating a Table",
      "Inserting Data",
      "Querying Data",
      "Updating Data",
      "Deleting Data",
      "Closing the Database",
      "Conclusion",
    ],
  },
  {
    id: "1B2D0884-6D5E-4A12-8CC5-160CA6B858DD",
    title: "Building a JSON Validation Pipeline with Go and Gin",
    description:
      "Imagine a scenario where we're transmitting crucial data from our website to a database. However, before this information is stored",
    titleSlug: "building-a-json-validation-pipeline-with-go-and-gin",
    date: "Aug 19, 2023",
    category: "backend",
    content: [
      "Full Code",
      "Import Statements",
      "Data Structures",
      "Main Function main()",
      "Router Function Router()",
      "ValidateBook Handler Function",
      "Reflection and Validation",
      "Test Using Thunder Client",
      "Test With CURL",
    ],
  },
  {
    id: "1F529938-65A4-48DA-82C1-D39917CB46E1",
    title: "Use Gin Web Framework to build your server",
    description:
      "Let's build a simple web service using the Go programming language and the Gin web framework. We will define a basic web server that listens for incoming HTTP requests and responds with JSON data.",
    titleSlug: "use-gin-web-framework-to-build-your-server",
    date: "Aug 19, 2023",
    category: "backend",
    content: [
      "Setup",
      "main.go",
      "web/assignments.go",
      "web/router.go",
      "Thanks for reading",
    ],
  },
  {
    id: "0ADA1327-7E22-477F-8B14-FFCCAE439697",
    title: "How to interact with Smart Contract?",
    description:
      "This article will teach you how to interact with a smart contract in the Ethereum blockchain, starting this article we first need to install some dependencies in our computer.",
    titleSlug: "how-to-interact-with-smart-contract",
    date: "Mar 22, 2023",
    category: "blockchain",
    content: [
      "Import ethers.js",
      "Set the provider",
      "Import the Contract ABI",
      "Connecting with Contract",
      "Fetching the DAI balance of an account",
      "Fetch the Token Details",
    ],
  },
  {
    id: "5B0C1002-0A2F-43C4-B3A8-F20A4DFAC9F3",
    title: "Fetch Balance from Ethereum Blockchain",
    description:
      "To Fetch the balance of an account in the Ethereum blockchain first we need to install some dependencies on our computer.",
    titleSlug: "fetch-balance-from-ethereum-blockchain",
    date: "Mar 17, 2023",
    category: "blockchain",
    content: [
      "Import Ethers.js",
      "Connect with a Node Provider",
      "Get an account address to fetch the balance",
      "Fetch balance",
      "Print the Balance in the console",
      "Full Code",
    ],
  },
  {
    id: "676B16D3-35F3-40EA-80E9-3A02635E35A6",
    title: "Blockchain Storage",
    description:
      "Learn about IPFS(InterPlanetary File System) and how we store data on blockchain. The blockchain contains some data, such as transactions or other information,",
    titleSlug: "blockchain-storage",
    date: "Feb 27, 2023",
    category: "blockchain",
    content: [
      "Introduction to blockchain storage",
      "Traditional storage vs blockchain storage",
      "Decentralized storage and its benefits",
      "Distributed ledger technology",
      "IPFS (InterPlanetary File System)",
      ["IPFS (InterPlanetary File System)", "Storage of data", "Versioning"],
      "Versioning",
    ],
  },
  {
    id: "10017BA2-D476-4BEF-8621-6E6B109CEF02",
    title: "Cryptography",
    description:
      "Cryptography is a huge topic and constantly evolving as the internet get advances. Here I will explain the topics that will help you understand blockchain better.",
    titleSlug: "cryptography",
    date: "Feb 23, 2023",
    category: "blockchain",
    content: [
      "Hash Function",
      "SHA256 Hash Function",
      "Nonce",
      "What is Encryption",
      "Symmetric Key Encryption",
      "Public Key Cryptography",
      "Secure Communication",
      "Digital Signatures",
      ["Adding a Digital Signature", "Verifying a Digital Signature"],
      "Certificate Authority",
      ["How does a Certificate Authority work?"],
      "What's on the next article?",
    ],
  },
  {
    id: "78BE0B8A-B0B2-49A2-BDCA-FB4B745F6B7A",
    title: "Decentralization with Blockchain",
    description:
      "How does the internet works? How the internet is centralized? What is Decentralization? Why it matters? Applications and uses of blockchain?",
    titleSlug: "decentralization-with-blockchain",
    date: "Feb 17, 2023",
    category: "blockchain",
    content: [
      "How does the internet works?",
      "How the internet is centralized?",
      "What is Decentralization?",
      "Why it matters?",
      "Applications and uses",
      "What's on the next article?",
    ],
  },
  {
    id: "B81ECCB3-E4C8-4DA9-8BB6-C744171747C7",
    title: "Blockchain Structure",
    description:
      "Understand how a blockchain work and what makes a blockchain. Today we are going to see how a blockchain work.",
    titleSlug: "blockchain-structure",
    date: "Feb 12, 2023",
    category: "blockchain",
    content: [
      "SHA256 Hash",
      "Block",
      "Blockchain",
      "Distributed Blockchain",
      "Tokens or Transaction",
      "Coinbase Transactions",
      "What's on the next article?",
    ],
  },
  {
    id: "EE437D7B-055E-485B-985B-CD9DD302E866",
    title: "What is Blockchain?",
    description:
      "Blockchain is a distributed ledger (ok but what this really mean ?). Let me explain it !",
    titleSlug: "what-is-blockchain",
    date: "Feb 8, 2023",
    category: "blockchain",
    content: [
      "Terminology",
      ["Immutability", "Distribution", "Ledger", "Node ( Host or Peer)"],
      "What's on the next article?",
    ],
  },
  {
    id: "0710C2D0-D1B1-4993-A3D0-BDD88805A31A",
    title: "Set up Tailwind in your Project",
    description:
      "Tailwind CSS is a utility class framework that helps you make a responsive web design. In this article, I will teach you, how to set up a tailwind in the project.",
    titleSlug: "set-up-tailwind-in-your-project",
    date: "Jan 19, 2023",
    category: "frontend",
    content: ["Play CDN ( Method 1)", "Tailwind CLI ( Method 2 )"],
  },
  {
    id: "F980A89E-C9D9-4FFA-AFCC-FB053F0D610F",
    title: "Git for Termux",
    description:
      "As the internet says git is a version control to track the code changes and there is not any second thought. I am not going to explain it in detail, If you want to read more",
    titleSlug: "git-for-termux",
    date: "Jan 26, 2022",
    category: "backend",
    content: [
      "Git",
      "Installation",
      ["step 1", "step 2", "What is Github?"],
      "Learn",
      ["Make Repository", "Push and Pull"],
      "Command table",
      "Thanks",
    ],
  },
  {
    id: "CA130AF4-E18A-436C-AAEF-AD87861D98FC",
    title: "Tmux for Termux",
    description:
      "Have you ever wonder how to open multiple sessions in a singel screen in termux. Here is a solution, an open source terminal multiplexer for Linux or Unix operating systems.",
    titleSlug: "tmux-for-termux",
    date: "Dec 19, 2021",
    category: "backend",
    content: ["Installation", "Basic command"],
  },
  {
    id: "F857DDBC-A889-4EBC-B0B9-B3B00B816283",
    title: "What is Cmatrix",
    description:
      "Want to see some animation in termux you can install cmatrix. Cmatrix shows cool matrix scrolling lines animation in terminal , you probably have seen in the Sci-fi movies.",
    titleSlug: "what-is-cmatrix",
    date: "Oct 16, 2021",
    category: "backend",
    content: ["Install", "Start and stop", "Colours", "More option", "Manual"],
  },
];

export type blogsType = {
  id: UUID;
  title: string;
  description: string;
  titleSlug: string;
  date: string;
  category: string;
  content: (string | string[])[];
};

export type ProjectType = {
  id: UUID;
  status:
    | "Concept"
    | "In Progress"
    | "Production"
    | "Archive"
    | "Beginner"
    | "Intermediate"
    | "Advance";
  title: string;
  subTitle: string;
  description: string;
  imageurl: string | null;
  path: string | null;
  link: string | null;
  source: string | null;
  bullets: string[];
  tags: string[];
  tasks: { id: UUID; title: string; subtitle: string }[];
};

export const projects: ProjectType[] = [
  {
    id: "7CF81AFA-D1CC-46B6-83B5-4309ADD993B6",
    status: "Beginner",
    title: "Blink LED using Arduino",
    subTitle:
      "A beginner-friendly Arduino project that demonstrates how to control an LED using digital output pins and basic Arduino programming.",
    description: `This project introduces beginners to the fundamentals of electronics and programming using Arduino. Students will learn how to control LEDs through simple code and gradually build more complex lighting patterns.Starting with a single LED, learners will understand how Arduino interacts with hardware using digital signals. As the course progresses, they will expand their knowledge by controlling multiple LEDs, adjusting timing, and creating dynamic effects such as running lights and reverse sequences. The project also introduces basic input handling by integrating a push button, allowing users to control LED behavior interactively.`,
    imageurl: "/image/blinklight.webp",
    path: "/projects/7CF81AFA-D1CC-46B6-83B5-4309ADD993B6",
    link: null,
    source: null,
    bullets: [],
    tags: ["Arduino", "IoT", "Electronics", "Microcontroller"],
    tasks: [
      {
        id: "C317ED1A-1010-4543-AE40-AC7A0A6C995E",
        title: "Setup & Overview",
        subtitle:
          "This task prepares students for the course by introducing the goal, required tools, and basic setup. It ensures everything is ready before starting hands-on tasks.",
      },
      {
        id: "D2353471-C30B-459A-B4DE-BA641DB9DC7D",
        title: "Blink One LED",
        subtitle:
          "Create your first Arduino program to blink a single LED ON and OFF repeatedly.",
      },
      // {
      //   id: "E7E632B8-F66F-403C-87D4-91DAE104951E",
      //   title: "Change Blink Speed",
      //   subtitle: "Modify the blinking speed by adjusting delay timing.",
      // },
      // {
      //   id: "80A81E71-2860-4D25-9E30-96E8A5F5FE51",
      //   title: "Blink Three LEDs Together",
      //   subtitle:
      //     "Control multiple LEDs at the same time using different pins.",
      // },
      // {
      //   id: "CC1EEF59-49C2-4540-9CC5-FBF9D66A5C73",
      //   title: "Blink LEDs in Sequence (Running Light)",
      //   subtitle:
      //     "Create a running light effect where LEDs turn ON one after another.",
      // },
      // {
      //   id: "EC177498-2C8D-4705-A768-9AA72CE76A98",
      //   title: "Reverse Sequence",
      //   subtitle: "Make LEDs move forward and backward in a loop.",
      // },
      // {
      //   id: "AB0C7131-3932-47D7-B783-F616FD4E6EE4",
      //   title: "Button Control (Optional Upgrade)",
      //   subtitle:
      //     "Use a push button to control LED behavior (like turning ON only when pressed).",
      // },
    ],
  },
];

export const urlshort = new Map<string, string>([
  [
    "class5",
    "https://docs.google.com/document/d/1j0mQvybUF-w393RdZ7Drhpps3FvGf59klgtdn8UotO0/edit?usp=share_link",
  ],
  [
    "class6",
    "https://docs.google.com/document/d/1cZGdnWY_t6Ck_J_4WGI8RGmqaaYHz5EDvyGNlqy2Big/edit?usp=share_link",
  ],
  [
    "class7",
    "https://docs.google.com/document/d/1r1nAO4kIiw6psiMPpMuzUpz2TSFl_5oYyq5ZkJ5MIwo/edit?usp=share_link",
  ],
    [
      "gimp",
      "https://fixthephoto.com/online-gimp-editor.html"
    ]
]);
